FeaturePanel and its elements
fullstacktf/fitness-frontend pull request #34
Opened 2020-12-13 18:52 UTC by raulrodrigueztorres

2020-12-14 09:34 UTC, raulanatol requested changes

2020-12-14 09:34 UTC, raulanatol commented on frontend/src/components/atomic/feature/Feature.tsx
>  }: FeatureProps): JSX.Element => {
No necesitas esos dos tipos ya que los infiere al decirle que el componente es un React.FC

```suggestion
}) => {
```

2020-12-14 09:34 UTC, raulanatol commented on frontend/src/components/atomic/feature/Feature.tsx
> +  if (direction === 'right') {
Es un poco redundante igual podrías solucionarlo con css (flex-direction) o unificando de algún modo el render para hacer un único return.

En caso de que no lo vean claro, es preferible hacer 2 returns:

if (direction === 'right') {
  return <>...</>;
}

return <>...</>;

2020-12-14 10:53 UTC, raulrodrigueztorres commented on frontend/src/components/atomic/feature/Feature.tsx
> +  if (direction === 'right') {
Acabo de modificar esta parte

2020-12-14 10:54 UTC, raulrodrigueztorres commented on frontend/src/components/atomic/feature/Feature.tsx
>  }: FeatureProps): JSX.Element => {
Me salta error si no los pongo, ¿se me escapa algo?

2020-12-15 14:13 UTC, pa-perz approved these changes
Pinta bien

2020-12-15 14:14 UTC, pa-perz commented on frontend/src/components/atomic/feature/Feature.tsx
>  }: FeatureProps): JSX.Element => {
El linter pide que se añada ese tipo aunque sea redundante

2020-12-15 14:15 UTC, merged