Added Team Members styles
fullstacktf/fitness-frontend pull request #36
Opened 2020-12-13 19:12 UTC by neikox

Team Member Panel styles

2020-12-14 09:27 UTC, raulanatol commented on frontend/.eslintcache
> +[{"/root/workspaces/fitness-frontend/frontend/src/components/atomic/button /Button.stories.tsx":"1","/root/workspaces/fitness-frontend/frontend/src/components/atomic/navbar-element/NavbarElement.stor
Cuidado con subir este fichero. Que crea muchos conflictos y es auto-generado.

2020-12-14 09:29 UTC, raulanatol requested changes, later dismissed

2020-12-14 09:29 UTC, raulanatol commented on frontend/src/components/atomic/team-member/TeamMember.tsx
> +      <Image src={pictureRoute} alt="" />
```suggestion
      <Image src={pictureRoute} alt={fullName} />
```
De este modo mantenemos algo de usabilidad.

2020-12-14 09:29 UTC, raulanatol commented on frontend/src/components/layout/team-member-panel/TeamMemberPanel.tsx
>  export const TeamMemberPanel: React.FC = (): JSX.Element => {
Al tiparlo como React.FC no necesitas tipar el result ya que lo infiere TS:

```suggestion
export const TeamMemberPanel: React.FC = () => {
```

2020-12-16 11:59 UTC, pa-perz approved these changes

2020-12-16 12:01 UTC, merged